### ISSUE TITLE
Eclipse disables lunar coin wipe on start of run

### ISSUE THREAD

**Issue by physixcat** [VarnaScelestus/RoR2#10]
It seems that playing on Eclipse effectively makes it so that coins are no longer ephemeral, while keeping the drop rate higher and the lunar shop cheaper. I assume this is because of the implementation of the new artifact

Could there be a way to make it detect when eclipse is being played, and apply the old effect without needing the artifact?

**Comment by VarnaScelestus** [comment]
Added a config option to do just that. It'll be out later today. See also #7
