### ISSUE TITLE
[Ephemeral Coins] Incompatibility with LunarCoinShareOnPickup

### ISSUE THREAD

**Issue by ConqAra** [VarnaScelestus/RoR2#12]
in multiplayer, when someone who's not host picks up a lunar coin with the new moon artifact on, the coins only go to the host while the other player remains with zero. (Idk if it's NECESSARILY an incompatibility with that mod, but when I pick up a coin it doesn't display an added coin either for them so I'm assuming it is)

ALTHOUGH it's appears to only be a visual bug, the player still has my amount of coins that we share function-wise, just still displays to them as "0" no matter how many they pick up.

**Comment by VarnaScelestus** [comment]
That's interesting. I'm not sure what the other mod touches so I'll have to look into it. Do your individual coin counts work properly with just Ephemeral Coins?

**Comment by ConqAra** [comment]
Well also quality of rain does this feature too and I had both of them on so I can try disabling quality of rain and retrying this feature first

**Comment by ConqAra** [comment]
also to answer your question- they work properly, it's just visually not showing and wont update the coin counter for the other person when it's suppose to share. it'll add the coins for both of us, just won't show up for the non-host

**Comment by ConqAra** [comment]
without LCSOP and with quality of rain, it doesn't work. 
without quality of rain and with LCSOP, it doesn't work.

Either way, regardless of the mod affecting lunar coin sharing, having this mod artifact enabled won't visually show the other player their lunar coins. It will stay at 0, even if THEY are the ones who pick them up and not the host.

**Comment by VarnaScelestus** [comment]
Changed the behavior of some hooks in [7e24ea9](https://github.com/VarnaScelestus/RoR2/commit/7e24ea9b81e59cecf7021d9284461ded650d5797) which should hopefully fix this issue.

**Comment by PollyEdaline** [comment]
This seems to be fixed for me in the newest update, although as per #15, clients don't seem to have their coin counts visually updated.

**Comment by VarnaScelestus** [comment]
Thanks for letting me know. I'll continue this in the other report.
