### ISSUE TITLE
EphemeralCoins: Mod does not load / Risk of Options dependency issue

### ISSUE THREAD

**Issue by VarnaScelestus** [VarnaScelestus/RoR2#13]
There is a known issue with how the soft dependency for Risk of Options was implemented, and I am working on a fix. For a temporary solution, please simply install Risk of Options to use the mod.

**Comment by VarnaScelestus** [comment]
Fixed in 2.2.1. In my quick testing the problem is solved, but if you experience any issues with this please let me know.

**Comment by WesCook** [comment]
Thanks for the quick fix.
