### ISSUE TITLE
Ephemereal Coins breaking the game for clients.

### ISSUE THREAD

**Issue by JardonKern** [VarnaScelestus/RoR2#14]
Everything was working fine 48 hours ago, but the recent updates seem to have borked the mod. I've tried playing with a friend but upon starting the run, he'll lag into the game rather than fade in and his drop pod won't even appear, remaining stuck in a sort of spectator mode clipping through the ground. Sometimes, he will spawn in normally but his ui will be stuck at 1 millisecond run timer, level 1, and hp bar graphical corruption.

Turning the newest artifact on/off in the config doesn't fix anything, nor does installing Risk of Options. 
I provide here 2 different logs (unity log and r2modman log) both from my friend (the client) and myself (the host). 

[client_LogOutput.log](https://github.com/VarnaScelestus/RoR2/files/8457001/client_LogOutput.log)
[client_output_log.txt](https://github.com/VarnaScelestus/RoR2/files/8457002/client_output_log.txt)
[host_LogOutput.log](https://github.com/VarnaScelestus/RoR2/files/8457003/host_LogOutput.log)
[host_output_log.txt](https://github.com/VarnaScelestus/RoR2/files/8457004/host_output_log.txt)

**Comment by VarnaScelestus** [comment]
As stated [here](https://github.com/VarnaScelestus/RoR2/issues/15#issuecomment-1094121297) I made some minor networking related changes that may impact this, but I can't be certain. If you could test again and provide logs (preferably with as few other mods as possible) I would appreciate it.

**Comment by PollyEdaline** [comment]
This was still happening on 2.2.2 when I tested. I am having a lot of difficulty with testing since I don't have anyone else to test with right now, but I managed to at least do a very quick test.

[LogOutput.log](https://github.com/VarnaScelestus/RoR2/files/8457894/LogOutput.log)

**Comment by VarnaScelestus** [comment]
> Larger rewrite in [2.3.0](https://github.com/VarnaScelestus/RoR2/commit/4b3098c301fafd4dab993ac5c3ca102b87620955) that should finally fix this. Learned a lot more about networking today than I ever wanted to know.

This issue was a bit bigger than 'coin counts not syncing', but I get the feeling with how bad the netcode was before it was causing a cascade of issues like this.

**Comment by tululum** [comment]
Hi, the mod is still making the game broken for client. On game start (first stage), client is always dead.
![image](https://user-images.githubusercontent.com/67554090/164973493-be87320a-1452-4c17-8ab4-1d373b3e3ade.png)

Only this mod and prerequisites are enabled.
![image](https://user-images.githubusercontent.com/67554090/164973566-c02fd616-4f01-4a59-872d-15082621e53e.png)

Log files:
[Client_LogOutput.log](https://github.com/VarnaScelestus/RoR2/files/8549527/Client_LogOutput.log)
[Host_LogOutput.log](https://github.com/VarnaScelestus/RoR2/files/8549528/Host_LogOutput.log)

Thanks for cool mod and hopefully this can be fixed as well. Thanks!

**Comment by VarnaScelestus** [comment]
> 

Your log shows that the client did not have the same mod list as the host, and their 'Fade Empty Chests' mod threw an exception that looks like it stopped the rest of their mods from even loading.

**Comment by tululum** [comment]
Whoops, here is the same issue without any other mods indeed on both server and client side:
[client2_LogOutput.log](https://github.com/VarnaScelestus/RoR2/files/8556794/client2_LogOutput.log)
[host2_LogOutput.log](https://github.com/VarnaScelestus/RoR2/files/8556795/host2_LogOutput.log)
