### ISSUE TITLE
[Ephemeral Coins] Clients do not have their coin counts visually updated

### ISSUE THREAD

**Issue by PollyEdaline** [VarnaScelestus/RoR2#15]
As of the latest patch, it seems that clients do not have their coin counts visually updated in the upper left corner. They are still tracked correctly and can be spent as normal, but only the host will have their coins correctly displayed.

Note that I do have a Lunar Coin sharing mod enabled. Here is a full output log just in case. I am using my modpack, Accretion, if you want to check the modlist there.

[LogOutput.log](https://github.com/VarnaScelestus/RoR2/files/8457222/LogOutput.log)

**Comment by VarnaScelestus** [comment]
I've made a minor change in an attempt to fix this in [2.2.2](https://github.com/VarnaScelestus/RoR2/commit/aeedfa93ba053a50867fd1eb1f813815056f71db), but I am unable to test since I only own one copy of the game and only have one pc. Let me know if this did anything to address the issue.

**Comment by VarnaScelestus** [comment]
Larger rewrite in (2.3.0)[https://github.com/VarnaScelestus/RoR2/commit/4b3098c301fafd4dab993ac5c3ca102b87620955] that should finally fix this. Learned a lot more about networking today than I ever wanted to know.
