### ISSUE TITLE
Incompatibility with RiskUI(?)

### ISSUE THREAD

**Issue by SOMSTATE** [VarnaScelestus/RoR2#19]
[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
EphemeralCoins.Hooks.HUD_Update (On.RoR2.UI.HUD+orig_Update orig, RoR2.UI.HUD self) (at <2f4f2b6b1832437b885874eda0dc65b9>:IL_004D)
DMD<>?-416477184.Hook<RoR2.UI.HUD::Update>?932042496 (RoR2.UI.HUD ) (at <64642b84b8744a1c89070cf2ede041fa>:IL_000A)

Only seems to happen with RiskUI Enabled.
Log file attached
[log2.txt](https://github.com/VarnaScelestus/RoR2/files/8643887/log2.txt)
.

**Comment by VarnaScelestus** [comment]
Should be fixed in [2.3.3](https://github.com/VarnaScelestus/RoR2/commit/056b6b1729b99884528be9dcfafa8206af7f25f2). Not enough time to look at RiskUI to do the subtle icon color change in their new HUD but this patch should at least stop the nullref spam.
