### ISSUE TITLE
I would love to see when OSP is triggered and having something to tell you for how long.

### ISSUE THREAD

**Issue by alexbaws159** [VarnaScelestus/RoR2#3]
I modded RoR2 heavily, I try to balance the game around almost impossibly hard difficulties. I did put OSP for a whole 1.0 second because otherwise, I just die instantly by the most innocent thing most of the time, but I think it would be fun to know how long that (grace period lasts), with a visual cue or anything (the easiest to implement, the better). I hesitated to post because it might be hard to implement and its definitely not an (issue) and more of a suggestion, but I am just putting this out there, I think it would be a cool addition to this mod.

**Comment by VarnaScelestus** [comment]
See: https://thunderstore.io/package/DestroyedClone/HealthbarImmune/

Haven't tested it, but in theory should work. I may add my own visual cue down the line but I have a lot of other work to do before considering that functionality.
