### ISSUE TITLE
New Update Incompatibility with multiplayer

### ISSUE THREAD

**Issue by ConqAra** [VarnaScelestus/RoR2#6]
Causes unplayable issues in multiplayer, starting with -2 coins when it was set to 0, and player fps is running at a fraction of what it normally is, as well as the game volume being very loud

**Comment by VarnaScelestus** [comment]
I'm sure this has to do with the larger can of worms I am working on as I write this. To be brief, there was an oversight in how the coin count was tracked, making it shared between host + clients, and causing a whole slew of networking related headaches. Hopefully I can fix this sometime tonight.

**Comment by VarnaScelestus** [comment]
Should be fixed by [32c3054](https://github.com/VarnaScelestus/RoR2/commit/32c30542ac9ac7ced97c097426a0d5ada560e812). I hope. Please keep me informed of any strange behavior. I'll leave this issue open for the moment.
