### ISSUE TITLE
Add option to not use Artifact at all

### ISSUE THREAD

**Issue by PollyEdaline** [VarnaScelestus/RoR2#7]
You can turn the Artifact off, but then the mod itself no longer seems to function. I prefer the old functionality of not having to use an Artifact. It would be nice if this was an option. If this is the intended function of the current setting then it does not work.

**Comment by VarnaScelestus** [comment]
Which part of the mod isn't working with the Artifact disabled? All the independent settings (coin drop chance, interactable costs, portal spawn rates, stuff like that) should still work without it.

**Comment by PollyEdaline** [comment]
Er, well, the main part of the mod, which is the ephemerality.

**Comment by PollyEdaline** [comment]
I guess for now I'll continue to use the old version of the mod or another mod that does something similar. Thank you!

**Comment by VarnaScelestus** [comment]
This was simpler to implement than I had anticipated and I have added it to the next version, which should be out sometime today.
